name: PhishTank URL Call

on:
  schedule:
    - cron: '0 16 * * */2'

jobs:
  phishtank_url_call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Extraction script
        run: |
          pip install gitpython
          rm -rf phishtank_url.csv
          wget https://data.phishtank.com/data/online-valid.csv -O phishtank_url.csv

      - name: Generate commit with extracted Content
        run: |
          git config --local user.name "${{ secrets.GIT_NAME }}"
          git config --local user.email "${{ secrets.GIT_MAIL }}"
          git add phishtank_url.csv
          git commit -m "$(TZ=Asia/Kolkata date +'%Y-%m-%d - %H:%M IST - PhishTank URL list')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}